export enum APIvars {
  domain = 'https://practical-pine-31844.pktriot.net',
  APIallowAll = '*',
  generateOTP = 'users/generateOTP',
  confirmotp = 'users/confirmotp',
  create_user = 'users/create',
  user_login = 'users/login',
  user_uploadDp = 'users/uploaddp',
  user_info = 'users/info',
  user_changeName = 'users/changeName',
  create_album = 'media/createAlbum',
  get_albums = 'media/getAlbums',
  get_album_details = 'media/getAlbumDetailsById',
  get_album_contents = 'media/albumContents',
  save_image = 'media/saveimages',
  delete_album = 'media/deleteAlbum',
  get_album_info = 'media/getAlbumInfo',
  update_album_info = 'media/updateInfo',
  get_album_link = 'media/getLink',
  get_image_info = 'media/getImageInfo',
  join_album_via_token = 'media/joinAlbumViaToken',
  leave_album_by_id = 'media/leaveAlbum'
}
